### PR TITLE
feat: position & content consistent comment removal

### LINKED ISSUE #43: Comment Free Dataset
As completed in #22, the comment-free dataset has been implemented. There are a few optimizations we can do

- [x] Maintain the same position for each context (Already done)
- [x] Maintain the same size for each context (fill with dummy code padding)
- [x] Move away from null characters (Nice to have)

### PR DESCRIPTION
**Pull request by JialeTomTian**
closes #43 to create a position and content-consistent comment removal evaluation. We do this by performing post-processing on the originally constructed context in `make_code_cotext`. Follows the steps:

1. Grab original constructed `prefix`, `needle_code` and `suffix` contexts
2. Remove comments from the components
3. Calculate the amount of tokens removed
4. Fill back the missing tokens using some dummy token

This approach guarantees that the comment-free context is content-consistent (i.e. the same code content just with the comments removed). The position may very slightly fluctuate (less than 1 percent difference in my testing) simply due to the dummy token used and the tokenizer

This code performs post-processing on the constructed context so no prior works should be impacted by this.

### CODE REVIEW

**Comment by UniverseFly** [comment]
One question: will the `"dummy"`s be included in the input context? Other changes look good.

**Comment by JialeTomTian** [comment]
Yes it would atm, open to feedback on more non-intrusive tokens that don't change the semantics of the code context.

**Comment by JialeTomTian** [comment]
Modified to use `language comment prefix` which is a more non-intrusive dummy token in terms of code understanding for the models.

**Comment by ganler** [comment]
A known issue is that if we have repeated "#\n", OAI will complain about the repeated patterns:

image

Not sure if we can hack by adding things like `# Comment {LINE_NO}`.

**Pull request merged**
